name: Convert Markdown to HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir -p docs
          for file in notes/*.md; do
              filename=$(basename "$file" .md)
              pandoc "$file" -s --template=templates/template.html -o "docs/$filename.html" --mathjax  --metadata title="$file"
          done

      - name: Upload Generated HTML as Artifact
        uses:  actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    needs: convert

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4