name: Convert Markdown to HTML

on:
  push:
    branches:
      - main  # Change this if your default branch is different
    paths:
      - 'notes/**/*.md'  # Only run when Markdown files in 'notes' change

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir -p docs
          for file in notes/*.md; do
              filename=$(basename "$file" .md)
              pandoc "$file" -s --template=templates/template.html -o "docs/$filename.html" --mathjax
          done
