name: Convert Markdown to HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir -p docs
          for file in notes/*.md; do
              filename=$(basename "$file" .md)
              pandoc "$file" -s --template=templates/template.html -o "docs/$filename.html" --mathjax
          done

      - name: Upload Generated HTML as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-artifact
          path: docs/  # Upload the generated HTML files in the docs folder

  deploy:
    needs: convert
    runs-on: ubuntu-latest
    steps:
      - name: Download HTML Artifact
        uses: actions/download-artifact@v4
        with:
          name: html-artifact

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Target GitHub Pages branch
          folder: docs